Repository dmlc/gluon-nlp, pull requests merged in 2019-06, with the labels that each got.

#734 [BUGFIX] [DOC] Update nlp.model.get_model documentation and get_model API
  docs/api/modules/model.rst
  src/gluonnlp/model/__init__.py
Labels: release focus

#612 [MODEL] BERT based NER
  scripts/bert/__init__.py
  scripts/bert/finetune_ner.py
  scripts/bert/index.rst
  scripts/bert/ner_common.py
  scripts/bert/ner_data.py
  scripts/bert/ner_model.py
  scripts/bert/predict_ner.py
Labels: release focus

#749 [BUGFIX] Fix handling of duplicate special tokens in Vocabulary
  src/gluonnlp/vocab/vocab.py
  tests/unittest/test_vocab_embed.py
Labels: bug, release focus

#733 [FEATURE] Add LAMB optimizer
  docs/api/modules/index.rst
  docs/api/modules/optimizer.rst
  src/gluonnlp/optimizer/__init__.py
  src/gluonnlp/optimizer/lamb.py
  tests/unittest/test_lamb.py
Labels: release focus

#743 [Enhancement] BERT pre-training data generation from sentencepiece vocab
  scripts/bert/create_pretraining_data.py
  scripts/bert/index.rst
  scripts/bert/pretraining_utils.py
  scripts/bert/run_pretraining.py
  scripts/bert/run_pretraining_hvd.py
  scripts/tests/test_scripts.py
  src/gluonnlp/data/stream.py
  src/gluonnlp/data/transforms.py
  src/gluonnlp/data/utils.py
  src/gluonnlp/model/bert.py
  src/gluonnlp/model/block.py
  src/gluonnlp/model/utils.py
  tests/unittest/test_models.py
  tests/unittest/test_transforms.py
Labels: release focus

#732 [FEATURE] Flexible vocabulary
  scripts/bert/utils.py
  setup.py
  src/gluonnlp/_constants.py
  src/gluonnlp/base.py
  src/gluonnlp/embedding/token_embedding.py
  src/gluonnlp/vocab/bert.py
  src/gluonnlp/vocab/vocab.py
  tests/data/vocab/backward_compat_0_7_corrupted_index
  tests/unittest/corpora/test_wikitext.py
  tests/unittest/test_bertvocab.py
  tests/unittest/test_vocab_embed.py
Labels: release focus

#752 [CI] Fix links in contribute.rst
  ci/jenkins/build_steps.groovy
  docs/community/contribute.rst
  docs/index.rst
Labels: release focus

#735 [MODEL] BERT conversion scripts, SciBERT, BioBERT, ClinicalBERT
  scripts/bert/conversion_tools/compare_tf_gluon_model.py
  scripts/bert/conversion_tools/convert_pytorch_model.py
  scripts/bert/conversion_tools/convert_tf_model.py
  scripts/bert/conversion_tools/infer_pytorch_gluon_parameter_name_mapping.py
  scripts/bert/conversion_tools/input.txt
  scripts/bert/index.rst
  scripts/bert/utils.py
  src/gluonnlp/data/utils.py
  src/gluonnlp/model/bert.py
  src/gluonnlp/model/utils.py
  tests/unittest/test_models.py
Labels: release focus

#750 [REFACTOR] Refactor TokenEmbedding to reduce number of places that initialize internals
  ci/jenkins/build_steps.groovy
  docs/conf.py
  src/gluonnlp/embedding/token_embedding.py
  src/gluonnlp/vocab/vocab.py
  tests/unittest/test_token_embedding.py
  tests/unittest/test_vocab_embed.py
Labels: release focus

#759 [MODEL]add baidu ernie model
  scripts/bert/conversion_tools/compare_gluon_ernie.py
  scripts/bert/conversion_tools/convert_paddle_to_gluon.py
  scripts/bert/conversion_tools/ernie_top_layer_emb.npy
  scripts/bert/conversion_tools/input_cn.txt
  src/gluonnlp/data/utils.py
  src/gluonnlp/model/__init__.py
  src/gluonnlp/model/bert.py
  src/gluonnlp/model/transformer.py
  tests/unittest/test_models.py
Labels: release focus

#763 [BUGFIX] Fix TokenEmbedding serialization with `emb[emb.unknown_token] != 0`
  src/gluonnlp/embedding/token_embedding.py
  tests/unittest/test_token_embedding.py
Labels: bug, release focus

#767 [API] Remove get_bert_model from the public API list
  scripts/bert/finetune_classifier.py
  scripts/bert/ner_utils.py
  src/gluonnlp/model/bert.py
Labels: API change

#761 [MODEL] GPT-2 for text generation
  ci/jenkins/Jenkinsfile_py2_cpu_unittest
  ci/jenkins/Jenkinsfile_py2_gpu_unittest
  env/cpu/py2.yml
  env/cpu/py3-master.yml
  env/cpu/py3.yml
  env/gpu/py2.yml
  env/gpu/py3-master.yml
  env/gpu/py3.yml
  pytest.ini
  scripts/machine_translation/train_transformer.py
  scripts/tests/test_models.py
  scripts/tests/test_scripts.py
  scripts/text_generation/__init__.py
  scripts/text_generation/index.rst
  scripts/text_generation/model/__init__.py
  scripts/text_generation/model/gpt.py
  scripts/text_generation/sequence_sampling.py
  src/gluonnlp/data/transforms.py
  src/gluonnlp/data/utils.py
  src/gluonnlp/model/sequence_sampler.py
  tests/unittest/test_sequence_sampler.py
  tests/unittest/test_transforms.py
Labels: release focus

#773 [BUGFIX] Fix glue test result serialization
  scripts/bert/finetune_classifier.py
Labels: release focus

#780 [Dataset] Move MRPC dataset to API
  scripts/bert/data/classification.py
  src/gluonnlp/data/glue.py
  tests/unittest/test_datasets.py
Labels: release focus

#739 [BiDAF-QANet] Common data processing logic for BiDAF and QANet
  scripts/question_answering/data_pipeline.py
  scripts/question_answering/data_processing.py
  scripts/question_answering/utils.py
  scripts/tests/conftest.py
  scripts/tests/test_question_answering.py
  src/gluonnlp/data/question_answering.py
Labels: release focus

#754 [API] Moving MaskedSoftmaxCELoss and LabelSmoothing to model API
  docs/examples/machine_translation/gnmt.md
  docs/examples/machine_translation/transformer.md
  scripts/machine_translation/__init__.py
  scripts/machine_translation/train_gnmt.py
  scripts/machine_translation/train_transformer.py
  src/gluonnlp/loss/__init__.py
  src/gluonnlp/loss/label_smoothing.py
  src/gluonnlp/loss/loss.py
  tests/unittest/test_loss.py
Labels: release focus

#793 [Enhancement] Mix precision support for BERT finetuning
  scripts/bert/finetune_classifier.py
  scripts/bert/index.rst
  scripts/bert/run_pretraining_hvd.py
  scripts/tests/test_scripts.py
  src/gluonnlp/model/attention_cell.py
Labels: release focus
