Repository dmlc/gluon-nlp, pull requests merged in 2020-07, with the labels that each got.

#1261 Update for Block API
  .github/workflows/unittests.yml
  README.md
  scripts/conversion_toolkits/convert_electra.py
  scripts/conversion_toolkits/convert_mobilebert.py
  scripts/conversion_toolkits/convert_tf_hub_model.py
  scripts/machine_translation/train_transformer.py
  scripts/pretraining/run_electra.py
  scripts/question_answering/models.py
  scripts/question_answering/run_squad.py
  src/gluonnlp/attention_cell.py
  src/gluonnlp/data/loading.py
  src/gluonnlp/initializer.py
  src/gluonnlp/layers.py
  src/gluonnlp/loss.py
  src/gluonnlp/lr_scheduler.py
  src/gluonnlp/models/albert.py
  src/gluonnlp/models/bert.py
  src/gluonnlp/models/electra.py
  src/gluonnlp/models/mobilebert.py
  src/gluonnlp/models/roberta.py
  src/gluonnlp/models/transformer.py
  src/gluonnlp/models/transformer_xl.py
  src/gluonnlp/optimizer.py
  src/gluonnlp/sequence_sampler.py
  src/gluonnlp/utils/misc.py
  tests/test_attention_cell.py
  tests/test_gluon_block.py
  tests/test_initializer.py
  tests/test_layers.py
  tests/test_models_electra.py
  tests/test_models_transformer.py
  tests/test_models_transformer_xl.py
  tests/test_sequence_sampler.py
  tests/test_utils_misc.py
Labels: release focus

#1264 Add fp16 support for Bert QA inference
  scripts/question_answering/run_squad.py
  src/gluonnlp/attention_cell.py
  src/gluonnlp/models/bert.py
Labels: enhancement, numpyrefactor

#1269 [Numpy] Refactor Roberta
  scripts/question_answering/README.md
  scripts/question_answering/eval_utils.py
  scripts/question_answering/models.py
  scripts/question_answering/run_squad.py
  src/gluonnlp/data/tokenizers.py
  src/gluonnlp/models/albert.py
  src/gluonnlp/models/bert.py
  src/gluonnlp/models/electra.py
  src/gluonnlp/models/mobilebert.py
  src/gluonnlp/models/model_zoo_checksums/roberta.txt
  src/gluonnlp/models/model_zoo_checksums/xlmr.txt
  src/gluonnlp/models/roberta.py
  src/gluonnlp/models/xlmr.py
  tests/test_data_tokenizers.py
  tests/test_models_roberta.py
  tests/test_models_xlmr.py
Labels: bug, numpyrefactor

#1282 [Numpy Refactor] BART
  scripts/conversion_toolkits/README.md
  scripts/conversion_toolkits/convert_bart.sh
  scripts/conversion_toolkits/convert_electra.py
  scripts/conversion_toolkits/convert_fairseq_bart.py
  scripts/conversion_toolkits/convert_fairseq_roberta.py
  scripts/conversion_toolkits/convert_mobilebert.py
  scripts/conversion_toolkits/convert_roberta.sh
  scripts/conversion_toolkits/convert_xlmr.sh
  scripts/machine_translation/README.md
  scripts/machine_translation/evaluate_transformer.py
  scripts/machine_translation/train_transformer.py
  scripts/machine_translation/wmt2014_back_translation.sh
  src/gluonnlp/layers.py
  src/gluonnlp/models/bart.py
  src/gluonnlp/models/model_zoo_checksums/bart.txt
  src/gluonnlp/models/transformer.py
  tests/test_models_bart.py
  tests/test_models_transformer.py
Labels: enhancement, numpyrefactor
